export const START_DATA_FETCH: string = 'START_DATA_FETCH'
export const SET_CHARACTERS_DATA: string = 'SET_CHARACTERS_DATA'
export const SET_LOADING: string = 'SET_LOADING'
export const SET_CURRENT_PAGE: string = 'SET_CURRENT_PAGE'
export const SET_CURRENT_OFFSET: string = 'SET_CURRENT_OFFSET'
export const SET_CURRENT_LANGUAGE: string = 'SET_CURRENT_LANGUAGE'
export const SET_CURRENT_CHARACTER_DATA: string = 'SET_CURRENT_CHARACTER_DATA'
export const START_SPECIFIC_CHARACTER_DATA_FETCH: string =
  'START_SPECIFIC_CHARACTER_DATA_FETCH'
